# Generated by Django 3.2 on 2021-05-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210508_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cdate',
            field=models.DateField(),
        ),
    ]
