# Generated by Django 3.2 on 2021-05-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_cdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cdate',
            new_name='date',
        ),
    ]
